spring:
  main:
    banner-mode: "off"

logging:
  level:
    root: ERROR 
    com.tukaloff.mediafstransfertool.*: INFO
    com.tukaloff.mediafstransfertool.MediaFsTransferToolApplication: ERROR
  config: "classpath:log4j2.xml"
